name: Download and Deploy
on:
  workflow_run:
    workflows: ["Build and Copy"] 
    types:
      - completed
jobs:
  deploy:
    name: Deploy Application
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: artifact
          github-token: ${{ github.token }} 
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: List Artifact
        run: ls -la artifact
          
