name: Run Bash Script on Self-Hosted Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: self-hosted # Runs on a self-hosted runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Delete Document Root Nginx
        run: |
          sudo rm -rf /var/www/html/*
      - name: Copy Webfiles to DocRoot
        run: |
          sudo cp -R project/* /var/www/html
        
        
      
