name: Build and Copy
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22  # Or your preferred Node.js version
      - name: Install dependencies
        run: |
          cd project
          npm install
          npm run build
      - name: Copy build directory to runner
        run: |
          mkdir -p /tmp/build
          cp -r .project/dist /tmp/build/
      - name: Upload build artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: /tmp/build

        
      
